#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
    configure)
        # Set the default settings of the service package to those expected by
        # OpenMediaVault.
        if [ -z "${2}" ] && [ -f /etc/systemd/system/subsonic.service ]; then
            systemctl stop subsonic.service >/dev/null || true
            systemctl disable subsonic.service >/dev/null || true
        fi

        SERVICE_XPATH_NAME="subsonic"
        SERVICE_XPATH="/config/services/${SERVICE_XPATH_NAME}"

        if ! getent passwd subsonic >/dev/null 2>&1; then
            adduser --quiet \
                    --system \
                    --ingroup users \
                    --no-create-home \
                    --disabled-password \
                    subsonic
        fi

        if [ -f "/var/run/subsonic.pid" ]; then
            PID=$(cat /var/run/subsonic.pid);
            kill -0 $PID 2>/dev/null;
            if [ $? -eq 0 ]; then
                kill -9 $PID;
                rm -Rf /var/run/subsonic.pid
            fi
        fi

        if ! omv_config_exists "${SERVICE_XPATH}"; then
            omv_config_add_node "/config/services" "${SERVICE_XPATH_NAME}"
            omv_config_add_node_data "${SERVICE_XPATH}" "enable" "0"
            omv_config_add_node_data "${SERVICE_XPATH}" "showtab" "0"
            omv_config_add_node_data "${SERVICE_XPATH}" "update" "0"
            omv_config_add_node_data "${SERVICE_XPATH}" "bupdate" "0"
            omv_config_add_node_data "${SERVICE_XPATH}" "port" "4040"
            omv_config_add_node_data "${SERVICE_XPATH}" "msg" "Not Installed."
        fi

        if ! omv_config_exists "${SERVICE_XPATH}/fork"; then
            omv_config_add_node_data "${SERVICE_XPATH}" "fork" "SubSonic"
        fi

        # Activate package triggers. These triggers are only set during the
        # package installation.
        dpkg-trigger update-fixperms
        dpkg-trigger update-locale

    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
